# name: Run periodically.

# on:
#   schedule:
#     - cron: '0 * * * *'
#   workflow_dispatch:
  
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: echo test
#       run: echo cron
