name: Do things every 1 minutes
on:
  schedule:
    - cron: "*/1 * * * *"
  push:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo test
        run: echo 'test'
